services:
  web:
    build: ./frontend
    ports:
      - "8082:8082"
  backendcontainer:
    build: ./backend
    ports:
      - "8080:8080"
  mymongodatabase:
    build: ./database
    environment:
     MONGO-INITDB-DATABASE: maindatabase
    ports:
     - "8083:27017"
